<?php

namespace Nemundo\Materialize\Form\Item;


use Nemundo\Com\Container\LibraryTrait;
use Nemundo\Com\FormBuilder\Item\AbstractDatePicker;
use Nemundo\Com\FormBuilder\Item\AbstractTextBox;
use Nemundo\Html\Form\Formatting\Label;
use Nemundo\Html\Formatting\Bold;

class MaterializeDatePicker extends AbstractTextBox  // AbstractDatePicker
{

    use LibraryTrait;

    public function getHtml()
    {

        $this->prepareHtml();

        $this->textInput->addCssClass('datepicker');

        $this->tagName = 'div';
        $this->addCssClass('input-field');

        $label = new Label();
        $label->content = $this->label;
        $label->for = $this->name;

        if ($this->showErrorMessage) {
            $bold = new Bold();
            $bold->content = $this->errorMessage;
            $label->content .= ' ' . $bold->getHtml();
        }

        $this->addContainer($this->textInput);
        $this->addContainer($label);

        $this->addJqueryScript('$(".datepicker").datepicker({ format: \'dd-mm-yyyy\' });');
        //$this->addJqueryCode('$(".datepicker").datepicker();');

        /*
        $(document).ready(function(){
            $('.datepicker').datepicker();
        });*/


        return parent::getHtml(); // TODO: Change the autogenerated stub
    }

}