<?php

namespace Nemundo\Materialize\Table;


use Nemundo\Html\Table\Table;

class MaterializeTable extends Table
{

    public function getHtml()
    {

        $this->addCssClass('striped');

        return parent::getHtml(); // TODO: Change the autogenerated stub
    }


}