<?php

namespace Nemundo\Materialize\Button;


use Nemundo\Com\Html\Hyperlink\SiteHyperlink;

class MaterializeButton extends SiteHyperlink
{

    /**
     * @var bool
     */
    public $disabled = false;

    public function getHtml()
    {

        $this->addCssClass('waves-effect waves-light btn');

        if ($this->disabled) {
            $this->addCssClass('disabled');
        }

        // <a class="waves-effect waves-light btn">button</a>

        return parent::getHtml(); // TODO: Change the autogenerated stub
    }


}